### PR TITLE
whole exome data from ICGC project THCA-SA. Issues included: 1. dupli…

### PR DESCRIPTION
**Pull request by hknahal**
…cated RG IDs in tumour/normal pairs. 2. duplicated SM. 3. empty PU. Replaced RG ID by concatenating existing RG ID with submitter_sample_id, replaced SM with submitter_sample_id, and made PU equal to RG ID

### CODE REVIEW

**Comment by junjun-zhang** [comment]
just a comment, I see the column `Sample (SM)` has been updated to match `submitter_sample_id`. It is meant to be the same as what's populated as `SM` in the BAM header, there is no need to change it. Such change will not be reflected in the generated SONG payload, there is no field as `sm_in_bam`

**Comment by hknahal** [comment]
@junjun-zhang The SM values were duplicated across files and tumour/normal BAMs (ie. same `SM` value used for both tumour and normal). Will this cause issues in the workflow?

**Comment by junjun-zhang** [comment]
whatever populated in the original BAM for `SM` does not have any impact on the alignment workflow (and downstream analysis). After the alignment workflow, within each aligned CRAM, the `SM` field of all read groups will be populated with ICGC Sample ID (ie, `SAxxxx`).

The reason, we look into `SM` field of the original submitted BAM is more for QC purpose, ie, ensure submitter acknowledges that the reads in the submitted BAM are indeed belonging to the sample (with submitter_sample_id) mentioned in the SONG payload.

**Comment by hknahal** [comment]
@junjun-zhang I reverted the change to the SM in the summary file: https://github.com/icgc-argo/argo-meta/pull/9

**Pull request merged**
