### PR TITLE
Added SONG payloads for 20 non-PCAWG WGS donors from PACA-AU

### PR DESCRIPTION
**Pull request by hknahal**
Summary Table: https://github.com/icgc-argo/argo-meta/blob/batch2-paca-au-non-pcawg_wgs/icgc_song_payloads/PACA-AU/WGS/summary_tables/batch2-non-PCAWG_PACA-AU_WGS_summary.tsv

### CODE REVIEW

**Comment by hknahal** [comment]
@lindaxiang I removed two SONG payloads (`EGAZ00001015379.json` and `EGAZ00001015344.json`) for donor ID `ICGC_0235` from this batch for now until I investigate why this PCAWG donor was missing in Collab initially. I will create a separate ticket for this PCAWG donor missing in Collab.

**Comment by lindaxiang** [comment]
sounds good to me.

**Comment by lindaxiang** [comment]
> @lindaxiang I removed two SONG payloads (`EGAZ00001015379.json` and `EGAZ00001015344.json`) for donor ID `ICGC_0235` from this batch for now until I investigate why this PCAWG donor was missing in Collab initially. I will create a separate ticket for this PCAWG donor missing in Collab.

@hknahal , do you want to remove these two payloads from the subfolder `batch2-non-pcawg` to avoid duplicates?

**Comment by hknahal** [comment]
> @lindaxiang I removed two SONG payloads (`EGAZ00001015379.json` and `EGAZ00001015344.json`) for donor ID `ICGC_0235` from this batch for now until I investigate why this PCAWG donor was missing in Collab initially. I will create a separate ticket for this PCAWG donor missing in Collab.

>> @hknahal , do you want to remove these two payloads from the subfolder `batch2-non-pcawg` to avoid duplicates?

Yes, you're right, I hadn't removed the duplicate files from the batch2 folder. They're removed now.

**Review by lindaxiang — APPROVED** [review]

**Pull request merged**
