### PR TITLE
Paca au rna seq

### PR DESCRIPTION
**Pull request by hknahal**
Changes made:

- In the original payloads, I mistakenly updated the existing read group ID. We normally do this if there are issues with the existing read group ID (update `submitter_read_group_id` with modified ID, and indicate what the original read group ID was in the `read_group_id_in_bam` field). I may have done this because there were issues with the read group IDs for TopHat BAMs and decided to do this right across for both Star and TopHat files. But the read group IDs in the Star BAM files look fine (no spaces), so I updated the existing payloads to keep the original read group ID name in the `submitter_read_group_id` field and set `read_group_id_in_bam` to `null`.
- There are 50 RNA-Seq donors in total that the APGI-AU program confirmed they have the required ARGO core clinical data (see [here](https://docs.google.com/spreadsheets/d/1X9QUJeFAFnkAAKattUnmljK2abSyTT8w/edit#gid=1199724826)). We have RNA-Seq data in Collab for 41 out of the 50 donors, so I removed the other payloads since we won't be able to include them in ARGO.

### CODE REVIEW

**Comment by lindaxiang** [comment]
@hknahal just want to clarify, 
- current `submitter_read_group_id` in the payloads are not the original read_group_id in the BAM header (I think this is my bad as I suggested Edmund to replace `:` to `_`. ) I thought we do not allow `:` in the `submitter_read_group_id`, but it looks like we do support. So maybe it's better to keep using the original `read_group_id`?

**Comment by hknahal** [comment]
@lindaxiang Thanks, I didn't realize the `:` were changed to `_`. Yes, if `:` is supported, then we should use the original read group ID. I'll update the payloads with the original read group IDs since I have the BAM headers.

**Comment by hknahal** [comment]
@lindaxiang @edsu7  I updated the `submitter_read_group_id` and `platform_unit` to match the original IDs in the BAM header files, since the `:` character is allowed and no modifications to the ID are required.

**Comment by lindaxiang** [comment]
@hknahal we will use the payloads under `trial_batch`, right? should we remove `batch1` and rename `trial_batch` to `batch1` to avoid confusions?

**Comment by hknahal** [comment]
@lindaxiang I removed the original `batch1` folder and renamed the `trial_batch` folder to `batch1` so it's consistent with the folder naming convention we've been using

**Review by lindaxiang — APPROVED** [review]
Looks great!

**Review by edsu7 — APPROVED** [review]
looks good from my end.

**Pull request merged**
