### PR TITLE
Payload migration

### PR DESCRIPTION
**Pull request by lindaxiang**

### CODE REVIEW

**Comment by junjun-zhang** [comment]
Is it OK to leave `donorId`, `specimenId`, `sampleId` in the `samples` section? Those are SONG managed fields. If they are ignored by the song update endpoint, it's ok.

Should `data_subtypes` field be present for all files even the value is `null`? This could be managed by the indexing step, so I am not what's the best here. Maybe it's OK for the field being missing.

**Review by junjun-zhang — APPROVED** [review]
if presence of `donorId`, `specimenId`, `sampleId` is not a problem, this is good to proceed

**Comment by lindaxiang** [comment]
> Is it OK to leave `donorId`, `specimenId`, `sampleId` in the `samples` section? Those are SONG managed fields. If they are ignored by the song update endpoint, it's ok.
> 
> Should `data_subtypes` field be present for all files even the value is `null`? This could be managed by the indexing step, so I am not what's the best here. Maybe it's OK for the field being missing.

@junjun-zhang , when update the dynamic portion in analysis, the `samples` and `files` are both took out. And it is unnecessary to keep `data_subtypes` field in the payloads if the value is `null` as they will be ignored by SONG anyway.  
I add the migration script. You can take a look and get my point.

**Comment by junjun-zhang** [comment]
> when update the dynamic portion in analysis, the samples and files are both took out. And it is unnecessary to keep data_subtypes field in the payloads if the value is null as they will be ignored by SONG anyway.
I add the migration script. You can take a look and get my point.

- `data_subtypes` under `files.info` is not **ignored** by SONG, just not validated. The script already has it in place even the value is `None`, so that's good.
- for what the script does, it's not really payload **migration**, it's payload **update**. Migration usually involves schema change, here there is no SONG schema change

**Review by hknahal — APPROVED** [review]

**Pull request merged**
